# Generated by Django 6.0.3 on 2026-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icerik', models.TextField(default='')),
                ('sira', models.IntegerField(default=0)),
            ],
        ),
    ]
