# Generated by Django 6.0.3 on 2026-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='dokumanlar/')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
