# Generated by Django 6.0.3 on 2026-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_dokuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('youtube_link', models.URLField()),
                ('aciklama', models.TextField(blank=True)),
                ('sira', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
    ]
