# Generated by Django 6.0.3 on 2026-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uygulama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('kod', models.TextField(blank=True)),
                ('sira', models.IntegerField(default=0)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
