# Generated by Django 6.0.3 on 2026-03-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_uygulama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uygulama',
            options={'ordering': ['sira']},
        ),
        migrations.CreateModel(
            name='VeriSeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True)),
                ('csv_dosya', models.FileField(blank=True, null=True, upload_to='veri_setleri/')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
