# Generated by Django 6.0.3 on 2026-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_kullaniciveri'),
    ]

    operations = [
        migrations.AddField(
            model_name='uygulama',
            name='icerik',
            field=models.TextField(blank=True, null=True, verbose_name='Uygulama Çalışma Alanı'),
        ),
        migrations.AlterField(
            model_name='uygulama',
            name='kod',
            field=models.TextField(blank=True, verbose_name='Python Kaynak Kodu'),
        ),
    ]
