# Generated by Django 6.0.3 on 2026-03-12 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_uygulama_icerik_alter_uygulama_kod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ders',
            options={'ordering': ['sira'], 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AddField(
            model_name='ders',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_konular', to='blog.ders', verbose_name='Üst Başlık (Boş bırakılırsa ana başlıktır)'),
        ),
    ]
