# Generated by Django 6.0.3 on 2026-03-12 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_ders_options_ders_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DersTamamlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlandi', models.BooleanField(default=False)),
                ('tamamlanma_tarihi', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ders')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'ders')},
            },
        ),
    ]
