# Generated by Django 6.0.3 on 2026-03-12 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_derstamamlama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derstamamlama',
            options={'verbose_name': 'Ders Tamamlama', 'verbose_name_plural': 'Ders Tamamlamaları'},
        ),
        migrations.AlterUniqueTogether(
            name='derstamamlama',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='derstamamlama',
            constraint=models.UniqueConstraint(fields=('kullanici', 'ders'), name='unique_kullanici_ders'),
        ),
    ]
