# Generated by Django 6.0.3 on 2026-03-12 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_derstamamlama_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ders',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_basliklar', to='blog.ders', verbose_name='Üst Başlık (Boş bırakılırsa ana başlıktır)'),
        ),
    ]
