# Generated by Django 6.0.3 on 2026-03-12 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_ders_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ders',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_dersler', to='blog.ders', verbose_name='Üst Başlık (Boş bırakılırsa ana başlıktır)'),
        ),
        migrations.CreateModel(
            name='AltBaslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField(blank=True, default='')),
                ('sira', models.IntegerField(default=0)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_basliklar', to='blog.ders')),
            ],
            options={
                'verbose_name_plural': 'Alt Başlıklar',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='AltBaslikTamamlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlandi', models.BooleanField(default=False)),
                ('tamamlanma_tarihi', models.DateTimeField(auto_now=True)),
                ('alt_baslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.altbaslik')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alt Başlık Tamamlama',
                'verbose_name_plural': 'Alt Başlık Tamalamaları',
                'constraints': [models.UniqueConstraint(fields=('kullanici', 'alt_baslik'), name='unique_kullanici_alt_baslik')],
            },
        ),
    ]
