# Generated by Django 6.0.3 on 2026-03-13 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_ders_parent_altbaslik_altbasliktamamlama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alistirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.TextField(help_text="Örn: Aşağıdaki değişkeni 'meyve' adıyla tanımlayın.")),
                ('kod_taslagi', models.TextField(help_text="Örn: ... = 'Elma'")),
                ('dogru_cevap', models.CharField(help_text='Örn: meyve', max_length=255)),
                ('ipucu', models.CharField(blank=True, max_length=255, null=True)),
                ('sira', models.PositiveIntegerField(default=0)),
                ('alt_baslik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alistirmalar', to='blog.altbaslik')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
    ]
